non-normative examples
primer4o6example2
	"Example: Snippet of ipo.xml with Substituted Elements from XML Schema Part 0: Primer Second Edition."

	^'<!-- .... -->
<items>
  <item partNum="833-AA">
    <productName>Lapis necklace</productName>
    <quantity>1</quantity>
    <USPrice>99.95</USPrice>
    <ipo:shipComment>
      Use gold wrap if possible
    </ipo:shipComment>
    <ipo:customerComment>
      Want this for the holidays!
    </ipo:customerComment>
    <shipDate>1999-12-05</shipDate>
  </item>
</items>
<!-- .... -->'