non-normative examples
primer5o6example1
	"Example: Using schemaLocation in the Quarterly Report, 4Q99html.xml from XML Schema Part 0: Primer Second Edition."

	^'<purchaseReport
  xmlns="http://www.example.com/Report"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.example.com/Report
  http://www.example.com/Report.xsd"
  period="P3M" periodEnding="1999-12-31">

  <!-- etc. -->

</purchaseReport>'