non-normative examples
ns5o1example0
	"Example: Applying Namespaces to Elements and Attributes: Namespace Scoping"

^'<?xml version="1.0"?>
<!-- all elements here are explicitly in the HTML namespace -->
<html:html xmlns:html=''http://www.w3.org/TR/REC-html40''>
  <html:head><html:title>Frobnostication</html:title></html:head>
  <html:body><html:p>Moved to 
    <html:a href=''http://frob.com''>here.</html:a></html:p></html:body>
</html:html>'